# Site settings
title: kauz
email: kauzlein@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kauz.github.io" # the base hostname & protocol for your site
github_username:  kauzlein

# Handling Reading
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "src"]

# Build settings
markdown: kramdown
sass:
  style: compressed
